server:
  port: 8080

spring:
  application:
    name: order-service

  h2:
    console.enabled: true
    datasource:
      url: jdbc:h2:mem:order;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 10
        delivery.timeout.ms: 120000